export type DividendYieldEntity = {
  id?: number;
  bankAccountId: number;
  bankAccountDescription?: string;
  symbol: string;
  paymentDate: string;
  yieldType: string;
  quantity: number;
  amount: number;
  total?: number;
};

export enum DividendYieldType {
  Rendiment = "RENDIMENT",
  JCP = "JCP",
  DividendYield = "DIVIDEND_YIELD",
}

// Generated by https://quicktype.io

export interface DyDashboardData {
  byYieldType: ByYieldType;
  byTicker: { [key: string]: number };
  totalDividendsLast12Months: number;
  barSeries: BarSerie[];
  monthArray: string[];
}

export interface BarSerie {
  data: number[];
  name: string;
}

export interface ByYieldType {
  JCP: number;
  RENDIMENT: number;
  DIVIDEND_YIELD: number;
}
