// Generated by https://quicktype.io

export interface IExpenseIncome {
  id: number;
  active: boolean;
  paymentType: string;
  dueDay: number;
  categoryId: number;
  categoryDescription: string;
  amount: number;
  history: string;
}
